version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    "caronc/apprise":
      versioning-strategy: "increase"
      schedule:
        interval: "daily"
    groups:
      all:
        patterns:
        - "*"
